### ISSUE TITLE
 are there Mac binaries prebuilt ? === configuring in external/secp256k1 ( /picocoin-master/external/secp256k1) configure: WARNING: no configuration information is in external/secp256k1

### ISSUE THREAD

**Issue by markmark1** [jgarzik/picocoin#103]
=== configuring in external/secp256k1 ( picocoin-master/external/secp256k1)
configure: WARNING: no configuration information is in external/secp256k1

unable to build

**Comment by xFAR** [comment]
Get https://github.com/bitcoin-core/secp256k1

place it within the pico tree ./external/, then autogen.sh, configure, make

**Comment by jgarzik** [comment]
Yep - @xFAR comments are valid - thanks.

**Comment by jgarzik** [comment]
`git submodule update` should also work?

**Comment by markmark1** [comment]
cd secp256k1/
marks-MBP:secp256k1 mark$ ls
marks-MBP:secp256k1 mark$ cd ..
marks-MBP:external mark$ cd secp256k1/
marks-MBP:secp256k1 mark$ ./autogen.sh ;configure;make
glibtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
glibtoolize: copying file 'build-aux/ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
glibtoolize: copying file 'build-aux/m4/libtool.m4'
glibtoolize: copying file 'build-aux/m4/ltoptions.m4'
glibtoolize: copying file 'build-aux/m4/ltsugar.m4'
glibtoolize: copying file 'build-aux/m4/ltversion.m4'
glibtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
-bash: configure: command not found
make: *** No targets specified and no makefile found.  Stop.
marks-MBP:secp256k1 mark$

**Comment by markmark1** [comment]
didn't work xFar

**Comment by markmark1** [comment]
:picocoin mark$ git submodule update
marks-MBP:picocoin mark$ ls
AUTHORS			README.md		external
COPYING			TODO			include
ChangeLog		autogen.sh		lib
LICENSE-3RD-PARTY.md	configure.ac		m4
Makefile.am		contrib			src
NEWS			doc			test
marks-MBP:picocoin mark$ cd external/secp256k1/
marks-MBP:secp256k1 mark$ git pull
Already up-to-date.
marks-MBP:secp256k1 mark$

**Comment by markmark1** [comment]
nothing happens with git submodule update jgarzik

**Comment by markmark1** [comment]
what are other spv bitcoin wallets you recommend?

**Comment by aido** [comment]
> nothing happens with git submodule update

Have you tried:
`git submodule update --init`
