### ISSUE TITLE
Wallet does not store addresses ?

### ISSUE THREAD

**Issue by steady286** [jgarzik/picocoin#107]
Hi Jeff,

i am using version v0.5 of picocoin (faa9b83a2).
When i do something like in the script below, i only get an empty wallet.
What am i doing wrong? Or do i need to upgrade ?  

Unfortunately, i am not able to compile the latest version, see bottom of this message
========== testrun ===============
`
PICOCOIN_PASSPHRASE="test"	
cmd="bin/picocoin0.5 --set=config=.picocoin/picocoin0.5.conf"

$cmd address
$cmd address
$cmd address
$cmd address
$cmd info
$cmd dump
`

i am getting only an empty wallet:
`
bitcoin@server:~$ ./picocoin05.sh 
1LpuWPHuDRoCQWCwS7pM1U66gXxDpsqR6D
1BNJHTMgu77T4ZZJxGSFt6HkYG8bnWPxPT
18uqEDigNh5SVL88Gfaq8E1dGAuPedUx8S
1JTy1AZ3iEFXJg4hqVxdccBjAAk1cybxyd
{
  "version": 1,
  "n_privkeys": 0,
  "n_hd_extkeys": 1,
  "netmagic": f9beb4d9
}
{
  "accounts": [
    {
      "acct_idx": 0,
      "name": "master",
      "next_key_idx": 213
    }
  ],
  "def_acct": "master",
  "hdmaster": [
    {
      "hdpriv": "9Xoy2u8vevhdokmLL5wks8mx6hGUKkU9LqBV1qLwiRaVMtAaqR3zm4RLFgD1VPCdRScwRpuUWfNnqDEMufFmJ9nkARoKw8kkSS2qJpVNZS"
    }
  ],
  "keys": [],
  "netmagic": "f9beb4d9",
  "version": 1
}
`
========== testrun end ===============

========== compile message ===========

`
gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I../include    -g -O2 -MT core.o -MD -MP -MF .deps/core.Tpo -c -o core.o core.c
mv -f .deps/core.Tpo .deps/core.Po
gcc -DHAVE_CONFIG_H -I. -I.. -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include   -I../include    -g -O2 -MT coredefs.o -MD -MP -MF .deps/coredefs.Tpo -c -o coredefs.o coredefs.c
mv -f .deps/coredefs.Tpo .deps/coredefs.Po
make[2]: *** No rule to make target `dns.c', needed by `dns.o'.  Stop.
make[2]: Leaving directory `/home/bitcoin/dev/picocoin/lib'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/bitcoin/dev/picocoin'
`
Thank you !

**Comment by steady286** [comment]
The build problem vanished, but i am still not able to store addresses. Thank you ..

**Comment by mpersano** [comment]
This probably happens because it's a deterministic wallet. Addresses are derived from the seed, so there's no need to explicitly store them in the wallet. (Though it would be nice if there was a command that would list addresses generated so far.)

**Comment by jgarzik** [comment]
Correct - we can see from `next_key_idx` that several keys have already been derived.
