### ISSUE TITLE
Payment Channels

### ISSUE THREAD

**Issue by martindale** [jgarzik/picocoin#26]
Payment channels, as described on [the Contracts wiki](https://en.bitcoin.it/wiki/Contracts#Example_7:_Rapidly-adjusted_.28micro.29payments_to_a_pre-determined_party) and implemented in [jgarzik/mcp](https://github.com/jgarzik/mcp), should be available in picocoin.

Adding here for tracking and discussion.

**Comment by jgarzik** [comment]
Concept ACK - idling out this issue

**Comment by martindale** [comment]
Great to get the ACK, @jgarzik!  Would you care to share some thoughts about the future of picocoin (maybe a 12 month roadmap)?  I remain extremely interested in getting payment channels working in that timeframe!

**Comment by jgarzik** [comment]
The focus is on a solid C library for bitcoin (libccoin), with the wallet piece remaining unloved (picocoin).

Implementing payment channels in the lib would be great.

Short term focus in simply keeping up with current BIPs, and removing OpenSSL.

**Comment by martindale** [comment]
Thanks, Jeff!  I wonder if @chjj would be interested in lending a hand.
