### ISSUE TITLE
autoreconf: automake failed with exit status: 1

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [jgarzik/picocoin#33]
What's the recommended compilation approach? Any log files? I think I've got all the dependencies installed too.

./autogen.sh 
Makefile.am: error: required file './README' not found
lib/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
test/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
autoreconf: automake failed with exit status: 1

**Comment by aido** [comment]
Hi ShaliDaliHaliDa,

I think this commit may be the cause of your problem:

https://github.com/jgarzik/picocoin/commit/01a08e87ef7fce4a4d3805a431d1dbaaf90e5695

Try renaming README.md back to README (or just copying it),

**Comment by ShaliDaliHaliDa** [comment]
thanks. I mv README.md to README and now autogen.sh doesn't error...

lib/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
test/Makefile.am:2: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')

but I don't see any binaries library anywhere? Am I missing something obvious?

**Comment by aido** [comment]
Hi ShaliDaliHaliDa,

Have you looked in the `src` directory?

**Comment by ShaliDaliHaliDa** [comment]
Hi aido,

The src directory has the lib .a 


-rw-r--r-- 1 root root  20474 Mar  1 21:09 Makefile
-rw-r--r-- 1 root root    715 Mar  1 20:33 Makefile.am
-rw-r--r-- 1 root root  21084 Mar  1 21:11 Makefile.in
-rw-r--r-- 1 root root   5830 Mar  1 20:33 aes.c
-rw-r--r-- 1 root root   9445 Mar  1 20:33 blkscan.c
-rw-r--r-- 1 root root   4791 Mar  1 20:33 blkstats.c
-rw-r--r-- 1 root root  36139 Mar  1 20:33 brd.c
-rw-r--r-- 1 root root    536 Mar  1 20:33 brd.h
-rw-r--r-- 1 root root 100980 Mar  1 21:10 brd.o
-rw-r--r-- 1 root root   4116 Mar  1 20:33 fakepoll.h
-rw-r--r-- 1 root root  30922 Mar  1 21:10 libnode.a
-rw-r--r-- 1 root root   7376 Mar  1 20:33 main.c
-rw-r--r-- 1 root root  25157 Mar  1 20:33 net.c
-rw-r--r-- 1 root root   8051 Mar  1 20:33 peerman.c
-rw-r--r-- 1 root root   1834 Mar  1 20:33 peerman.h
-rw-r--r-- 1 root root  30588 Mar  1 21:10 peerman.o
-rw-r--r-- 1 root root   1047 Mar  1 20:33 picocoin.h
-rw-r--r-- 1 root root  11377 Mar  1 20:33 rawtx.c
-rw-r--r-- 1 root root   9537 Mar  1 20:33 wallet.c
-rw-r--r-- 1 root root    626 Mar  1 20:33 wallet.h

I was expecting a picocoin binary?

**Comment by aido** [comment]
Hi ShaliDaliHaliDa,

You are executing the following commands?

 ```
./autogen.sh
./configure
make
```

**Comment by ShaliDaliHaliDa** [comment]
Perfect thank you. Sorry I was skipping the make, thought I had run it already.

**Comment by aido** [comment]
Hi ShaliDaliHaliDa,

Maybe leave this issue open as automake.sh does not work until README.md is renamed to README?

**Comment by ShaliDaliHaliDa** [comment]
sure np, I re-opened the case.

**Comment by jgarzik** [comment]
fixed
