### ISSUE TITLE
wallet: Missing PICOCOIN_PASSPHRASE for AES crypto

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [jgarzik/picocoin#34]
I've compiled pico coin but when I try create a new wallet i.e.
sudo ./picocoin new-wallet

wallet: Missing PICOCOIN_PASSPHRASE for AES crypto
wallet: failed to store picocoin.wallet

Do I need to set the PICOCOIN_PASSPHRASE somewhere?

**Comment by aido** [comment]
Hi ShaliDaliHaliDa

From README:

`Passphrase is specified via environment variable PICOCOIN_PASSPHRASE.`

Rather than raising an issue for each of you queries maybe raise them in the forum instead.

**Comment by ShaliDaliHaliDa** [comment]
Thanks aido. Unfortunately bitcointalk.org doesn't seem to load for me. I've been trying for a few days now and fear it might be blocked in my country? I was able to view the content via proxy but didn't find any sample config files. I'll keep looking.
