### ISSUE TITLE
Sample configuration file

### ISSUE THREAD

**Issue by ShaliDaliHaliDa** [jgarzik/picocoin#35]
Does anyone have a sample configuration file?

**Comment by aido** [comment]
Hi ShaliDaliDa,

A quick look at the `main.c` code shows the commands and settings used by the picocoin binary:

https://github.com/jgarzik/picocoin/blob/master/src/main.c#L224

Also, the `const_settings` variable right at the top of `main.c` shows what a config file will contain:
https://github.com/jgarzik/picocoin/blob/master/src/main.c#L41
