### ISSUE TITLE
ipv6 prefix in net.C   2011:0470/36

### ISSUE THREAD

**Issue by jacobbogers** [jgarzik/picocoin#67]
HI Jgarzik,
in the net.c module i see in function "bn_group" the code snippet

2011:0470/36 ipv6 prefix is unassigned, what are you checking for precisely?

_  else if (ipaddr[GB(15)] == 0x20 && ipaddr[GB(14)] == 0x11 &&
                 ipaddr[GB(13)] == 0x04 && ipaddr[GB(12)] == 0x70)
                bits = 36;
}
else  bits = 32;_

**Comment by aido** [comment]
Hi @jacobbogers,

This old bug in bitcoin core may help answer:

https://github.com/bitcoin/bitcoin/commit/a5e685bcf8eea088ba2eea544dcf2b0ac29ff6cc
