### ISSUE TITLE
block relay deamon

### ISSUE THREAD

**Issue by jacobbogers** [jgarzik/picocoin#68]
Hi Jgarzik,

what does the block relay deamon (brd executable) do? Its commandline options are not described (as compared to picocoin executable), so, its not really needed?

**Comment by aido** [comment]
Hi @jacobbogers

You may get answers to your queries by posting in the forum:
https://bitcointalk.org/index.php?topic=128055.0

While reading through the forum you may see this comment about the block relay daemon:
https://bitcointalk.org/index.php?topic=128055.msg2583846#msg2583846

**Comment by jacobbogers** [comment]
Hi Aido,

There is only a mention of the "block relay daemon", not what it actually
does

Anyway.  I will try to ask in the forum, thanks

**Comment by jacobbogers** [comment]
I became a member of the forum, and i tried to post for the first time but
it refused, saved my message as a draft???

Is this normal??? anyone had this experience before?

Jacob

**Comment by aido** [comment]
Hi @jacobbogers,

https://bitcointalk.org/index.php?topic=15958.0

**Comment by jacobbogers** [comment]
Thanks,

My first post has been accepted...

Jacob

Aido, I have a problem with libgmp, configure says its missing but it is
installed according to yum

CentOS EL7.2
---

$sudo yum install gmp

Package 1:gmp-6.0.0-12.el7_1.x86_64 already installed and latest version


$./configure
checking for __gmpz_init in -lgmp... no
configure: error: Missing required libgmp


thats weird?  is the "__gmpz_init" absent in version 6.0?


 find /usr -iname "*gmp*.so"

/usr/lib/openssl/engines/libgmp.so
/usr/lib64/openssl098e/engines/libgmp.so
/usr/lib64/openssl/engines/libgmp.so

**Comment by aido** [comment]
Hi @jacobbogers

Try installing libgmp-dev and running ./configure again.

**Comment by jacobbogers** [comment]
Its running,
Its seems the "brd" and "picocoin" executable use different files for peers
and block database should these be configured to be the same? see the same
peers and see the same blocks?

 brd.peers
 brd.blocks
 picocoin.blkdb
 picocoin.peers

**Comment by aido** [comment]
Hi @jacobbogers

Please refer to my original response to your original query:
https://bitcointalk.org/index.php?topic=128055.msg2583846#msg2583846

And maybe also the following post on the forum (which is probably the best pace for your comments):
https://bitcointalk.org/index.php?topic=128055.msg6676351#msg6676351

**Comment by jacobbogers** [comment]
HI Aido,

I clicked the 2 links , there is no explanation of *what* a block relay
daemon is its only mentioned
https://bitcointalk.org/index.php?topic=128055.msg2583846#msg2583846
(quote)  --> The two clients, "brd" (block relay daemon) and "picocoin"
(SPV client) remain incomplete and have not seen much attention.

https://bitcointalk.org/index.php?topic=128055.msg6676351#msg6676351

Only mentioned that brd writes to some files, not what it does.

I will try to make a post on the forum, I have a lot of questions, I hope
the forum will not limit my posts as before.
Can you answer my  question in email?  what does the brd (conceptually) do?

Thanks for your efforts
Jacob

**Comment by jacobbogers** [comment]
(continue).

Yes)) I have posted successfully,.., hope to see you on the forum))

Are you in IRC #bitcoin?


Jacob

**Comment by jacobbogers** [comment]
Hi all could you help me answer some questions I posted on bitcointalk.
As you see I am doing my best to understand the code
Maybe it's a good idea to put all of this into a doc/ directory akin to
what the Linux kernel does. I don't think it's performance to go through
this with very new guy.
I am now at the point where the first message is sent on connecting with a
peer (brd daemon).   Just a question what IDE do you use on Linux. I am
just using VI, but I find it a bit of a pain.  What IDE works well with
autotools?

**Comment by aido** [comment]
> What IDE works well with autotools?

Personal choice really:
https://c9.io/

**Comment by jacobbogers** [comment]
You program C picocoin code with an online IDE?  ....
Thats a new one ..... coool)

**Comment by jacobbogers** [comment]
Aiodo, Jgarzik, hi,

Did you see my gitter invitation,

Anyway, I am trying to get my head around the block locater object.
how do i detect i am on the wrong chain?
