### ISSUE TITLE
use of argp  in rawtx.c but not in picocoin and brd

### ISSUE THREAD

**Issue by jacobbogers** [jgarzik/picocoin#70]
Hi,

Is it a good idea to have picocoin and brd use argp aswell?,  I think argp was later introduced after picocoin and brd were written or is there a reason not to use it in picocoin, brd and possible others?

I would like to convert,

**Comment by jgarzik** [comment]
Yes; argp is available on many non-Linux platforms.

**Comment by jacobbogers** [comment]
Hi   I am converting the command line options of picocoin and brd to argp,
 also including an option to only get ipv4 addresses from the seeds (my
ADSL modem is not ipv6 capable).  Will let you know when it is done for you
to take a look and see if it is something you approveof

**Comment by jacobbogers** [comment]
Hi All,

I see some options that are not documented in the markdown README.md

static const char *const_settings[] = {
        "net.connect.timeout=11",
        "chain=bitcoin",
        "peers=brd.peers",
        /* "blkdb=brd.blkdb", */
        "blocks=brd.blocks",
        "log=-", /* "log=brd.log", */
};


peers,
blocks
log

I want to try to move to argp, aka Should these be hidden options when
using argp ?

Greets,
