### ISSUE TITLE
Coverity static analysis

### ISSUE THREAD

**Issue by aido** [jgarzik/picocoin#71]
Hi,

Coverity static analysis can easily be added to picocoin by adding something like the following to `.travis.yml`:
```
.
.
env:
  global:
    - secure: "W4D9Wmi+kJbxJuekKXJnhp665L2ljUuq5jrXmRqBwRDIZxbQi/mJqBEVcHEf/3W3l9W67pLd+mvV0cVv9g0AQ/nkUCSj5JCNJrePeovaQmf1QHluTa+bDUABa68X1sx201uj4EmkGJJHtYkv3Cimucut1C4g83eGXajnptKinqyLnUg9ji8aYmv7wm8n12VFeMM7+RyR53MT0nuPpCEw0hRQJQxKzXq/qw/5Wb0vBU1IovNX6bFQNMgTcHEXpppIh7efaAM50v4lj3zd5ZgLDuREmss/HriuJD3KUCWUoVgOkg+QUyW4IAIiI/dWSX9PJYtf1rKhc4ANwjq828NzyhbMJWlOBOBVAZxg+xWmc5+I+mHgmV/YylTMN4+sFnFi9gdDjmF8ImsME2qjDXm1txFknLeNP4CCEHKYCcgsNGPKUtrn2L9Be99HMScBqy7nmCQyhKvTWnYc7j/Je6PjEkXYNT96VNwZ4U8mXktkNPcYkQ43oMbUplITGiA8s50vuWQTLGjFjj+cxgAsz0rOc7+RSVxogY+MkP3+Fc28BKu1ZLLTvAmADWR+xd/179JnL+IAzM5eHUInlIp56DZF7nDoYFyt/yw3VCRUYPNOXVXzY8vCVGI+Hcr+MjmgDu7lhUeTvREaR3iJjEV3QutN79KYKr+CEeRVIoxOBigRVj4="
    - MAKEJOBS=-j3
.
.
addons:
  coverity_scan:
    project:
      name: "jgarzik/picocoin"
      description: "Build submitted via Travis CI"
    notification_email: jgarzik@users.noreply.github.com
    build_command_prepend: "./autogen.sh; ./configure; make clean"
    build_command: "make check"
    branch_pattern: master
.
.
```

And maybe a nice badge in `README.md`.
```
[![Coverity Scan Build Status](https://scan.coverity.com/projects/8288/badge.svg)](https://scan.coverity.com/projects/jgarzik-picocoin) 
```

See:
https://github.com/aido/picocoin/commit/9ce5f09f333105d05b3c72a09eb4bff79bef945c

I haven't added this as a pull request as the keys, project number etc. will be different for jgarzik/picocoin.

The Coverity scan at https://scan.coverity.com/projects/aido-picocoin currently finds 28 defects; some high impact, others low.

I have the following components configured:

| Component name | Pattern | Ignore
| --- | --- | ---
| lib | .\*/lib/.\* | No
| ccoin | .\*/include/ccoin/.\* | No
| src | .\*/src/.\* | No
| test | .\*/test/.\* | No
| external | .\*/external/.\* | Yes

Coverity suggest creating a separate coverity branch and merging from master occasionally to trigger a scan.
For projects with fewer than 100K lines of code the number of allowed weekly builds per project are up to 12 builds per week, with a maximum of 3 builds per day. Picocoin is well within these limits so probably no need for a separate coverity branch for now.

**Comment by jacobbogers** [comment]
Hi,  I have never seen Travis.yml.  what does it do?

**Comment by aido** [comment]
Hi @jacobbogers,

https://docs.travis-ci.com/user/for-beginners

https://travis-ci.org/jgarzik/picocoin

**Comment by jacobbogers** [comment]
Thanks very much for explaining


On Thursday, April 21, 2016, Aido <notifications@github.com> wrote:
>
> Hi @jacobbogers <https://github.com/jacobbogers>,
> <https://docs.travis-ci.com/user/for-beginners>
> https://docs.travis-ci.com/user/for-beginners
<https://docs.travis-ci.com/user/for-beginners>
> <https://travis-ci.org/jgarzik/picocoin>
> https://travis-ci.org/jgarzik/picocoin
<https://travis-ci.org/jgarzik/picocoin>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
<https://github.com/jgarzik/picocoin/issues/71#issuecomment-213082019>

**Comment by jgarzik** [comment]
Nice.  I just signed up.  Travis-CI example comes with some easy cut-and-paste.  Will set it up and badge ourselves when I get some free time.

**Comment by aido** [comment]
Hi,

I am seeing the following error for all the Travis builds on my fork of picocoin:

`Coverity Scan API access denied. Check $PROJECT_NAME and $COVERITY_SCAN_TOKEN.`

In hindsight I think it may be better to have a separate coverity branch in jgarzik/picocoin and merging from master branch occasionally to trigger a scan. Otherwise forks of the master branch will cause all Travis builds to fail for all users except jgarzik.

**Comment by jgarzik** [comment]
@aido Thanks for the advice.  Updated.

Anxiously awaiting the actual list of defects!   They require a wait before revealing the list.

**Comment by aido** [comment]
Hi,

If you really can't wait here's a Coverity scan done just before your recent burst of commits:

https://scan.coverity.com/projects/aido-picocoin

35 defects and some nice graphs. I think a lot of those 35 outstanding defects are false positives.

**Comment by jgarzik** [comment]
@aido Great - Sent you a request for access

**Comment by jgarzik** [comment]
Coverity found several minor bugs, and one major bug.
