### ISSUE TITLE
code: "Warning" because truncation of 64 bit integer 

### ISSUE THREAD

**Issue by jacobbogers** [jgarzik/picocoin#73]
https://bitcoin.org/en/developer-reference#compactsize-unsigned-integers
I have a question about this piece of code related to the link above
module: serialize.c

The *WARNING* in the code below because uint64_t is truncated to uint32_t

I dont understand the specs in the link above say otherwise, is there a reason for this?

function: 
` bool deser_varlen(uint32_t *lo, struct const_buffer *buf)
{
        uint32_t len;
        unsigned char c;

        if (!deser_bytes(&c, buf, 1)) return false;

        if (c == 253) {
                uint16_t v16;
                if (!deser_u16(&v16, buf)) return false;
                len = v16;
        }
        else if (c == 254) {
                uint32_t v32;
                if (!deser_u32(&v32, buf)) return false;
                len = v32;
        }
        else if (c == 255) {
                uint64_t v64;
                if (!deser_u64(&v64, buf)) return false;
                len = (uint32_t) v64;   /* WARNING: truncate */
        }
        else
                len = c;

        *lo = len;
        return true;
}
`

**Comment by jgarzik** [comment]
In this case 64-bit integers hold a maximum 32-bit value
