### ISSUE TITLE
brd.c function "nc_msg_addr"  needlessly parsing addresses if protover <   CADDR_TIME_VERSION

### ISSUE THREAD

**Issue by jacobbogers** [jgarzik/picocoin#74]
HI,

I see in this function the bp_adresses are fetched from the buffer but later on if the conn->protover is < CADDR_TIME_VERSION it is discarded, can we move this up front to the top of the function?

static bool nc_msg_addr(struct nc_conn *conn)
{
.
. if (!deser_msg_addr(conn->protover, &ma, &buf))
                goto out;
.
.

        /* ignore ancient addresses */                     <-- move this to beginning of function?
        if (conn->protover < CADDR_TIME_VERSION)
                goto out_ok;
.
.
}

**Comment by jgarzik** [comment]
possible, yes
