### ISSUE TITLE
OpenSSL fails , is returning '0'     EC_KEY_new_by_curve_name(NID_secp256k1)

### ISSUE THREAD

**Issue by jacobbogers** [jgarzik/picocoin#76]
in key.c .....key->k = EC_KEY_new_by_curve_name(NID_secp256k1);

I have 2 bitcoin clients failing on this api call 'picocoin' and "bitc" 
My openSSL version on CENTOS is 

OpenSSL 1.0.1e-fips 11 Feb 2013

How to fix this?
```

bool bp_key_init(struct bp_key *key)
{
        memset(key, 0, sizeof(*key));

        key->k = EC_KEY_new_by_curve_name(NID_secp256k1);
        if (!key->k)
                return false;

        return true;
}
```

**Comment by aido** [comment]
Hi @jacobbogers,

#66 fixes this.
